
EE_BIN = ../build/memoryTest.elf
EE_OBJS = memoryMain.o 

.PHONY: all

all: $(EE_BIN)

.PHONY: clean
clean:
	rm -f *.o $(EE_BIN)

include $(PS2SDK)/Defs.make
include ../make/Makefile.pref
include ../make/Makefile.eeglobal
