
EE_BIN = ../build/complex.elf
EE_OBJS = main.o 


.PHONY: all


all: $(EE_BIN) 


.PHONY: clean
clean:
	rm -f *.o $(EE_BIN)

include $(PS2SDK)/Defs.make
include ../make/Makefile.pref
include ../make/Makefile.eeglobal
